language: node_js

node_js:
  - "8.9.4"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/siba_db

before_script:
  - psql -c 'create database siba_db;' -U postgres
  - psql -U postgres -d siba_db -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
