language: node_js

node_js:
  - "8.9.4"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/sibaDB

before_script:
  - psql -c 'create database sibaDB;' -U postgres
  - psql -U postgres -d sibaDB -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
