language: node_js
node_js:
  - "v8.0.0"

env:
  - DB=postgresql://postgres@localhost:5432/sibaDB



before_script:
  - psql -c 'create database sibaDB;' -U postgres
  - psql -U postgres -d sibaDB -a -f tables.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2
