language: node_js

envi:
    - DB=postgresql://postgres@localhost:5432/usersDB

node_js:
  - "v8.0.0"

before_script: 
  - psql -c 'create database usersDB;' -U postgres
  - psql -U postgres -d usersDB -a -f tables.sql

addons:
    apt:
      packages:
          -postgresql-server-dev-9.2

